/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package annotation.user;

public class App {

    public static void main(String[] args) {
        Employee employee = new EmployeeBuilder()
            .age(24)
            .name("James")
            .build();
    }
}
